services:
  - type: web
    name: credit-risk-scoring
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
